# How to fill in your secrets:
#   git clone https://github.com/matter-labs/era-consensus.git
#   cd era-consensus/node
#   cargo run -p zksync_consensus_tools --bin keys
# 
# You might need to install some compilation dependencies manually (like clang).
# Copy the node public/secret keys from the output and paste below.

# node:public:ed25519:???
node_key: 'node:secret:ed25519:???'
