name: Workflow template for Core Linting CI jobs
on:
  workflow_call:

jobs:
  build:
    runs-on: [matterlabs-ci-runner]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup environment
        run: |
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env
      - name: Start services
        run: |
          ci_localnet_up
      - name: Build
        run: |
          ci_run bash -c "cd zk_toolbox && cargo build --release"
      # Compress with tar to avoid permission loss
      # https://github.com/actions/upload-artifact?tab=readme-ov-file#permission-loss
      - name: Tar zk_toolbox binaries
        run: |
          tar -C ./zk_toolbox/target/release -cvf zk_toolbox.tar zk_inception zk_supervisor
      - name: Upload zk_toolbox binaries
        uses: actions/upload-artifact@v4
        with:
          name: zk_toolbox
          path: zk_toolbox.tar
          compression-level: 0

  code_lint:
    runs-on: [matterlabs-ci-runner]
    needs: [build]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Download zk_toolbox binaries
        uses: actions/download-artifact@v4
        with:
          name: zk_toolbox
          path: .

      - name: Extract zk_toolbox binaries
        run: |
          tar -xvf zk_toolbox.tar -C ./bin

      - name: Setup environment
        run: |
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Start services
        run: |
          ci_localnet_up
          ci_run sccache --start-server

      - name: Lints
        run: |
          ci_run zks fmt --check
          ci_run zks lint -e md --check
          ci_run zks lint -e sol --check
          ci_run zks lint -e js --check
          ci_run zks lint -e ts --check
          ci_run zks lint -e rs --check
