name: Workflow template for CI jobs against docs
on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        description: "DOCKERHUB_USER"
        required: true
      DOCKERHUB_TOKEN:
        description: "DOCKERHUB_TOKEN"
        required: true
jobs:
  lint:
    runs-on: [matterlabs-ci-runner]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: "recursive"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Start services
        run: |
          mkdir -p ./volumes/postgres
          run_retried docker compose pull zk postgres
          docker compose up -d zk postgres

      - name: Lints
        run: |
          ci_run zk
          ci_run zk fmt md --check
          ci_run zk lint md --check
